
; PIC16F887 Configuration Bit Settings

; ASM source line config statements

#include "p16F887.inc"

; CONFIG1
; __config 0xFFF1
 __CONFIG _CONFIG1, _FOSC_XT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_ON
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF


     LIST p=16F887
     
var1 equ 0x20
VAL_HIGH equ .127
VAL_LOW	 equ .64
LED_RED  equ 0
LED_GREEN equ 1
LED_YELLOW equ 2
LED_VERDE equ 0
LED_AMARILLO equ 1
LED_ROJO equ 2
 
 
    org	0x00

    MOVLW .0
    MOVWF var1

CONFIG_LED
    ;BANK 1
    BCF STATUS,RP1  ;RP1 = 0
    BSF STATUS,RP0   ;RP0 = 1
    MOVLW b'11111000'	;SET RB0, RB1, RB2 AS OUTPUT
    MOVWF TRISB
    ;BANK 0
    BCF STATUS,RP0
    CLRF PORTB
  
VERIF_HIGH
    MOVF var1,0
    SUBLW VAL_HIGH
    BTFSC STATUS,C
    GOTO VERIF_LOW
    GOTO LED_VERDE_FUNC
 
VERIF_LOW
    MOVF var1,0
    SUBLW VAL_LOW
    BTFSC STATUS,C
    GOTO LED_ROJO_FUNC
    GOTO LED_AMARI_FUNC    
    
LED_VERDE_FUNC
    BSF PORTB,LED_VERDE ;RB0 = 1
    BCF PORTB,LED_AMARILLO  ;RB1 = 0
    BCF PORTB,LED_ROJO  ;RB2 = 0
    GOTO INC_VAR

LED_AMARI_FUNC
    BCF PORTB,LED_VERDE ;RB0 = 0
    BSF PORTB,LED_AMARILLO  ;RB1 = 1
    BCF PORTB,LED_ROJO  ;RB2 = 0
    GOTO INC_VAR
   
LED_ROJO_FUNC
    BCF PORTB,LED_VERDE ;RB0 = 0
    BCF PORTB,LED_AMARILLO  ;RB1 = 0
    BSF PORTB,LED_ROJO  ;RB2 = 1
    GOTO INC_VAR
    
INC_VAR
    INCF var1,1
    GOTO VERIF_HIGH
    
    
    
    
    
    
    MOVLW .130
    MOVWF var1
    SUBLW .127
    BTFSC STATUS,C
    GOTO DEC_MED
    GOTO LED_GREEN_FUNC

DEC_MED
    MOVF var1,0
    SUBLW .64
    BTFSC STATUS,C
    GOTO LED_RED_FUNC
    GOTO LED_YELLOW_FUNC
  
INIT
    MOVF var1,0
    XORLW VAL_HIGH
    BTFSS STATUS,Z
    DECF var1,1
    BTFSS STATUS,Z
    GOTO LED_GREEN
    BTFSS PORTB,0
    GOTO LED_RED
     
    MOVLW 0x0a
    
;CONFIG

    
LED_RED_FUNC
    BSF PORTB,LED_RED
    BCF PORTB,LED_GREEN
    BCF PORTB,LED_YELLOW
    GOTO INIT
    
LED_GREEN_FUNC
    BSF PORTB,LED_GREEN
    BCF PORTB,LED_RED
    BCF PORTB,LED_YELLOW
    GOTO INIT
        
LED_YELLOW_FUNC
    BSF PORTB,LED_YELLOW
    BCF PORTB,LED_RED
    BCF PORTB,LED_GREEN
    GOTO INIT
    
    end